# Generated by Django 3.2.6 on 2021-09-27 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='response',
            field=models.BooleanField(null=True),
        ),
    ]
