# Generated by Django 3.2.6 on 2021-10-01 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_alter_review_ticket'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserFollows',
        ),
    ]
