# Generated by Django 3.2.6 on 2021-09-09 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('age', models.CharField(max_length=2)),
            ],
            options={
                'verbose_name': 'Nom et Age',
            },
        ),
    ]
